language: ruby
rvm:
  - 2.4.1
cache: bundler
install: gem install jekyll html-proofer
before_script:
 - git clone https://github.com/szbpsz/theme.git tmp
 - cp -r tmp/* ./
 - rm -r -f tmp
script: jekyll build && htmlproofer ./_site