language: ruby
rvm:
  - 2.4.1
cache: bundler
install: gem install jekyll
before_script:
 - git clone https://github.com/szbpsz/theme.git tmp
 - cp -r tmp/* ./
 - rm -r -f tmp
 - bundle install
script: bundle exec jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true