language: ruby
rvm:
- 2.4.1
cache: bundler
install: gem install jekyll
before_script:
- git clone https://github.com/szbpsz/theme.git tmp
- cp -r tmp/* ./
- rm -r -f tmp
- bundle install
script: bundle exec jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Cl+4gFdpUWZu8nuZ/2QaeSpxjnG5Hgkp5UrGZmLLn/HYhlarV0BRb4EvE8ROWtM8L9lnoBRxyaaylUlflrA3HOf4SuS+KoxmI7QejB8mJZVwQ6wbjJk5/ssUtzcmICPG8GzFsMLJqHJ4sCSV/xPKzRtUmqmR4RMvEKDR0o4PguiRqmNjRY5iLBNJvlIZCqM88GGT0Qfnougc8H9VcC1shxRpjzfqgOMmUujXa8lDLcjPkkjr8hnnT5p85wSifVIweTi2Al9573G53r3D/heE9Jso75jDKGKXMj2zUGzdzNIfJAzr+oRfp1xcN1QgKBJcNW1fk3AJTCbq0NbdWNMPPjQleZ3g39IDju84e4E9FZjB03Q1JT3i3cG2xYKyIYY7vo24bvgpnOD5nv9Bn4H6BMVJeW6vBsos05K8CPEL1Xhb1o++np5MpwgotbEgpDyvKYkJaHIEeOd8Q4xkcls9AFq8HMWlg7Ixmkooy96q6nrG3RD/DqVWFZ/P5mOg/YoXGvdcEkNUaYW2HMthDU0YJHUAYSWnCkXU91uN2DUt/imj7R8sRBWV35W0s1Hn9tW4bXmEzguln9AVxsQY2YgL2/rf1lj5NclG8POlFY43fFpYGSjb3XfL4B9O303ic1fgqvY6U4h2v9jBkBaHQowCzCWCMu92WUJjeb9hqSbgfS0=
  - secure: elIZa8Nk4getjH4/g7hp/0T2X2iJDt+nuzyGf2u4uKAjmA3CVNZTlnyfLJ7PfxL7K8hXFdfQCjFAHpRZutxnuVFQPOedUQ0qcMFnKT7wm2kkAFd1R0Ogk6urLBriRSltnzWuhmvEW/I5r8+4eyRt2d1EXOkxNTbLknHCpn2gs4CKrMPRcYo2OwDgMyaFpTQGNVAdc4JavZ2Oy1dC+UWPW0tG0gwQppAPcrerXnl0zVmrO9br5Cgo2ytIC/JhF2bQmbiOcOgR3y0v2idsaMXhLmk8Fa9KrUl3SnqaL+NMsijHie5gs6GorZyasZQRptEfx/RokzXSGsxjvOseiTKJ1wbmUfPdj5TMuD5DNEDUYC6uRqP8/8DADLACmjyvh6DYOgngDMWS3dUP8lWln+EhtkLK5tCE2DJZCa1V+gD7hySDrrEcOLBeM55xj0z2h0ht4G4SW4MhPE/5AFhQk0tuB4WHU69UsKBC2d+w8xO6D6MlJSV7dzXReWlbh+8Hws4L2dKFmSWpe7zASOw4yACyJPAz2SneDl1SGoqpVq3EJz/yZFSKQrElUVZDKuioeb7YY6pIw5Baiq0+AM8X7XNs1T5uzN5p/TzkfdAxuQidi57XzB7+f4YlSJCpvlZE8C5H6nphVZfIYjfpyqJzVszBtdJUQfMDW1Gv5QOC94CWV8w=
  - secure: vUomHFqmIBb5pGpvFY1UVSebLJ3IcXAiVuHhiSbRS2a8EpfbD7fl15g2y8VC47lJ+qkcp6HC3PNn/0TplLqecChckAFqyJF924QEg/HECfqYrUpwXQZnm8gLeWXRGafaKYSFYipb5CZo6SHWcK/+MnkZq4Ys02gZZPl6sJUtY9Hs2Kyc72MuFXxbOpdf+oq4YrHgYq3WjIExZ1G4fevFw5Nk2eXXXmqUcxc4Acs+p1487SirMzDNBjLuAQym2UJdYCV29TUhQbvKTRxjWaM5foqZ4uHoFXi3k2popmSFvnIl9z3apq1lZ9rARz4JYKXK6SrljZMtiKOAlTZk2nu5UOlOHKtvc4IB06n/gC5OPbqMh6uPD1wcKjylFFyh5jehmir/v01Bq6gFDcLMwaS/7cZYVfA5uBnilm1Gs4GmN541c4sT0rCU0QrkiM5dm86YyDfervw0SBv/9zRYvd1LECgsrVHGsXx3Y1Pjg+N6xPSC/C+3JjyiAe0qZQmB8VDKucnXn0W6GMs8c7CgFWfFuz4vavL0xI4hUZ9rzGaf6h1ZCb/jvQOoMG9XhbKLgI5f3pPWRk+0+dzIFqsEF3f8/hprHiJt42/S8EI9KsWaXh69MJl77bKkrJoZP4jHMp+BwK0kjLBhR6Zof+mWBmBbaSVOp4XAAHoqK5wV3WmfPG0=
deploy:
  skip_cleanup: true
  provider: firebase
  project: "szbpsz-d612a"
  token:
    secure: "FIREBASE_DEPLOY_TOKEN"